---
version: '3'

services:

  dumb:
    image: dumb-docker-registry-ui:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5858:5858"
    volumes:
      - "./config/dumb.yml:/config/dumb.yml:ro"
      - "./src:/app/src"
